GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/648f1e17c6770f1914bf8c58

###
DELETE http://localhost:3001/api/notes/648f862901302d12e7a1163a

###
POST http://localhost:3001/api/notes/
Content-Type: application/json

{
    "content": "Ensure that everything still works",
    "important": true
}

###
PUT http://localhost:3001/api/notes/6490ba5ac05502e0d40ca63a
Content-Type: application/json

{
    "content": "Ensure that everything still works",
    "important": true
}