DELETE http://localhost:3001/api/persons/4

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
    "name": "Arto Helaaaa", 
    "number": "123-456-7890"
}


###
GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons
