###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
    "name": "Arto Helaaaa", 
    "number": "123-456-7890"
}

###
GET http://localhost:3001/api/persons/648f304cfff9450e0b9819bf

###
DELETE http://localhost:3001/api/persons/648f304cfff9450e0b9819bf

###
PUT http://localhost:3001/api/persons/648f31011c1368f34dd14402
Content-Type: application/json

{ 
    "name": "Arto Lovelace", 
    "number": "123-456-7890"
}